--- 
- hosts: all 
  become: yes
  tasks:
      - name: i want to install java 8 verion on ubuntu node
        apt:
           name: openjdk-8-jre
           state: present 
        when: ansible_os_family=="Debian"



      - name: i want to install java 8 version RedHat node
        yum:
           name: java-1.8.0-openjdk
           state: present 
        when: ansible_os_family=="RedHat"