--- 
- hosts: webserverhost
  become: yes
  tasks:
      - name: i want to install java 8 verion on ubuntu node
        apt:
           name: "{{myjavapackageforubuntu}}"
           state: present 
        when: ansible_os_family=="Debian"



      - name: i want to install java 8 version RedHat node
        yum:
           name: "{{myjavapackageforredhat}}"
           state: present 
        when: ansible_os_family=="RedHat"