--- 
- hosts: 172.31.5.99 
  become: yes
  tasks: 
     - name: i want install tree 
       apt:
          name: tree 
          state: present
       tags: mytree 
          

     - name: i want install wget
       apt: 
          name: wget
          stateee: present
       tags: mywget 


     - name: i want to install git 
       apt:
           name: git
           state: present
       tags: mygit