--- 
- hosts: webserverhost
  become: yes
  tasks:
        - name: i want to install webserver on ubuntu node
          apt:
             name: "{{mywebserveronubuntu}}"
             state: present
          when: ansible_os_family=="Debian"

        - name: i want to start/stop webserver on ubuntu node
          service:
             name: "{{mywebserveronubuntu}}"
             state: started
          when: ansible_os_family=="Debian"


        - name: i want to install webserver on RedHat node
          yum:
             name: "{{mywebserveronredhad}}"
             state: present
          when: ansible_os_family=="RedHat"

        - name: i want to start/stop webserver on Redhat node
          service:
             name: "{{mywebserveronredhad}}"
             state: started
          when: ansible_os_family=="RedHat"


        