--- 
# Step 4.1 :  Give the tomcat group ownership over the entire installation directory
- name: Recursively change ownership of a directory /opt/tomcat
  file:
    path: /opt/tomcat
    state: directory
    recurse: yes
    owner: tomcat
    group: tomcat

# Step 4.2 :  give the tomcat group read access to the conf directory 
- name: give the tomcat group read access conf directory 
  file:
    path: /opt/tomcat/conf
    recurse: yes
    owner: tomcat
    group: tomcat
    mode: g+r

# Step 4.3 :  give the tomcat group execute access to the conf directory 
- name: give the tomcat group read access conf directory 
  file:
    path: /opt/tomcat/conf
    owner: tomcat
    group: tomcat
    mode: g+x
# Step 4.4.1 :  Make the tomcat user the owner of the webapps
- name: Make the tomcat user the owner of the webapps
  file:
    path: /opt/tomcat/webapps
    state: directory
    recurse: yes
    owner: tomcat
    group: tomcat

# Step 4.4.2 :  Make the tomcat user the owner of the work
- name: Make the tomcat user the owner of the work
  file:
    path: /opt/tomcat/work
    state: directory
    recurse: yes
    owner: tomcat
    group: tomcat


# Step 4.4.3 :  Make the tomcat user the owner of the temp
- name: Make the tomcat user the owner of the temp
  file:
    path: /opt/tomcat/temp
    state: directory
    recurse: yes
    owner: tomcat
    group: tomcat


# Step 4.4.4 :  Make the tomcat user the owner of the logs
- name: Make the tomcat user the owner of the logs
  file:
    path: /opt/tomcat/logs
    state: directory
    recurse: yes
    owner: tomcat
    group: tomcat